# Generated by Django 4.1.6 on 2023-10-30 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(default='a', max_length=200)),
                ('last_name', models.CharField(default='a', max_length=200)),
                ('gender', models.CharField(default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patient', models.CharField(max_length=200)),
                ('id_hospital', models.CharField(max_length=200)),
                ('id_doctor', models.CharField(max_length=200)),
                ('id_session', models.CharField(default='1', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(default='a', max_length=200)),
                ('last_name', models.CharField(default='a', max_length=200)),
                ('gender', models.CharField(default='m', max_length=1)),
                ('day', models.CharField(default='1,2', max_length=200)),
                ('id_hospital', models.CharField(max_length=200)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.session')),
            ],
        ),
    ]
