# Generated by Django 4.1.6 on 2023-11-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id_session',
        ),
        migrations.AddField(
            model_name='doctor',
            name='session',
            field=models.CharField(default='a,a', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='menunggu', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='day',
            field=models.CharField(default='a,a', max_length=200),
        ),
    ]
