# Generated by Django 4.1.6 on 2023-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0003_doctor_birth_date_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
