# Generated by Django 4.1.6 on 2023-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_alter_doctor_birth_date_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(default='2003-10-02'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default='2003-10-02'),
        ),
    ]
