# Generated by Django 4.1.6 on 2023-11-02 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_alter_doctor_birth_date_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=datetime.date(2003, 10, 2)),
        ),
    ]
