# Generated by Django 4.1.6 on 2023-11-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='massage_doctor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='massage_patient',
            field=models.TextField(default=''),
        ),
    ]
