# Generated by Django 4.1.6 on 2023-11-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0008_reservation_massage_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='massage_doctor',
            new_name='message_doctor',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='massage_patient',
            new_name='message_patient',
        ),
    ]
