# Generated by Django 4.1.6 on 2024-05-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0012_alter_board_userid_alter_image_userid_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='urlgambar',
        ),
        migrations.AddField(
            model_name='image',
            name='nama',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
