# Generated by Django 4.1.6 on 2024-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0013_remove_image_urlgambar_image_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
