# Generated by Django 4.1.6 on 2024-05-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myFirstApp', '0014_image_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=300)),
                ('source', models.ImageField(blank=True, null=True, upload_to='')),
                ('boardid', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.board')),
                ('userid', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
